# CMake generated Testfile for 
# Source directory: /Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util
# Build directory: /Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/python/mujoco/util
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ArrayTraitsTest.CArrayType "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.CArrayType")
set_tests_properties(ArrayTraitsTest.CArrayType PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.ArrayNdim "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.ArrayNdim")
set_tests_properties(ArrayTraitsTest.ArrayNdim PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.ArrayScalarType "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.ArrayScalarType")
set_tests_properties(ArrayTraitsTest.ArrayScalarType PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.MakeEigen "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.MakeEigen")
set_tests_properties(ArrayTraitsTest.MakeEigen PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.IsCallable "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.IsCallable")
set_tests_properties(FuncTraitsTest.IsCallable PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.FuncArgType "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.FuncArgType")
set_tests_properties(FuncTraitsTest.FuncArgType PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.FuncArgCount "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.FuncArgCount")
set_tests_properties(FuncTraitsTest.FuncArgCount PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncWrapTest.UnwrapArgs "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/func_wrap_test" "--gtest_filter=FuncWrapTest.UnwrapArgs")
set_tests_properties(FuncWrapTest.UnwrapArgs PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;87;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncWrapTest.ReturnArrayArg0 "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/func_wrap_test" "--gtest_filter=FuncWrapTest.ReturnArrayArg0")
set_tests_properties(FuncWrapTest.ReturnArrayArg0 PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;87;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(TupleToolsTest.Slice "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/tuple_tools_test" "--gtest_filter=TupleToolsTest.Slice")
set_tests_properties(TupleToolsTest.Slice PROPERTIES  _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;96;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/python/mujoco/util/CMakeLists.txt;0;")
