# CMake generated Testfile for 
# Source directory: /Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity
# Build directory: /Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/test/plugin/elasticity
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PluginTest.CantileverIntoCircle "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/cable_test" "--gtest_filter=PluginTest.CantileverIntoCircle")
set_tests_properties(PluginTest.CantileverIntoCircle PROPERTIES  WORKING_DIRECTORY "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/CMakeLists.txt;26;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.InvalidTxtAttribute "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/cable_test" "--gtest_filter=PluginTest.InvalidTxtAttribute")
set_tests_properties(PluginTest.InvalidTxtAttribute PROPERTIES  WORKING_DIRECTORY "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/CMakeLists.txt;26;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.InvalidMixedAttribute "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/cable_test" "--gtest_filter=PluginTest.InvalidMixedAttribute")
set_tests_properties(PluginTest.InvalidMixedAttribute PROPERTIES  WORKING_DIRECTORY "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/CMakeLists.txt;26;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.ValidAttributes "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/build_mujoco/bin/cable_test" "--gtest_filter=PluginTest.ValidAttributes")
set_tests_properties(PluginTest.ValidAttributes PROPERTIES  WORKING_DIRECTORY "/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test" _BACKTRACE_TRIPLES "/opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/GoogleTest.cmake;400;add_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/CMakeLists.txt;26;gtest_add_tests;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/qkatlehdrnf/SynologyDrive/github/opai_ros/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
